AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Cloudformation template for media exchange publisher and subscriber shared CMK setup.

Outputs:
  SubscriberOnboardingSummary:
    Description: Configuration information for subscriber as key-value
    Value:
      Fn::Join:
        - ' '
        - - Fn::Sub: NAME=${SubscriberName}
          - Fn::Sub: AWS_REGION=${AWS::Region}
          - Fn::Join:
            - ''
            - - BUCKET_NAME=
              - Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-publisher-${PublisherName}-bucketname
          - Fn::Join:
            - ''
            - - PREFIX=
              - Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-prefix
          - Fn::Join:
            - ''
            - - ROLE=
              - Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-role

  PublisherOnboardingSummary:
    Description: Configuration information for publisher as key-value
    Value:
      Fn::Join:
        - ' '
        - - Fn::Sub: NAME=${PublisherName}
          - Fn::Sub: AWS_REGION=${AWS::Region}
          - Fn::Join:
            - ''
            - - BUCKET_NAME=
              - Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-publisher-${PublisherName}-bucketname

          - Fn::Join:
            - ''
            - - SUBSCRIBER_PREFIX=
              - Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-prefix

          - Fn::Join:
            - ''
            - - SUBSCRIBER_CANNONICAL_ACCOUNTID=
              - Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-cannonicalaccountid

          - Fn::Sub: KMSMANAGEDMASTERKEY=${CMK.Arn}

          - Fn::Join:
            - ''
            - - ROLE=
              - Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-publisher-${PublisherName}-role

          - Fn::Join:
            - ''
            - - EVENT_BUS_NAME=
              - Fn::ImportValue:
                  Fn::Sub: mxc-${AWS::Region}-${Environment}-events


Metadata:

  License:
    Description: |
      Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.

      Permission is hereby granted, free of charge, to any person obtaining a copy of this
      software and associated documentation files (the "Software"), to deal in the Software
      without restriction, including without limitation the rights to use, copy, modify,
      merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
      permit persons to whom the Software is furnished to do so.

      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
      INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
      PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
      HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
      OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
      SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Deployment Configuration"
        Parameters:
          - Environment
      -
        Label:
          default: "Agreement Configuration"
        Parameters:
          - PublisherName
          - SubscriberName


Parameters:
  Environment:
    Type: String
    Description: Deployment Environment Name
    Default: dev

  PublisherName:
    Type: String
    Description: The name of the publisher, case sensetive, as registerd in this Media Exchange deployment.

  SubscriberName:
    Type: String
    Description: The name of the subscriber, case sensetive, as registerd in this Media Exchange deployment.


Resources:

  CMK:
    Type: AWS::KMS::Key
    Properties:
      Description: Symetric Key for Encrypting Objects in Media Exchange
      Enabled: true
      EnableKeyRotation: true
      PendingWindowInDays: 7
      KeyPolicy:
        Version: 2012-10-17
        Id: node-key-policy
        Statement:
          -
            Sid: KeyManagement
            Effect: Allow
            Principal:
              AWS:
                - Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
                # - Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/mxc-${Environment}-${AWS::Region}-sc-product-role
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:TagResource
              - kms:UntagResource
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
            Resource: '*'
          -
            Sid: SubscriberAccess
            Effect: Allow
            Principal:
              AWS:
                - Fn::Join:
                  - ':'
                  - - 'arn:aws:iam:'
                    - Fn::ImportValue:
                        Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-accountid
                    - root

            Action:
              - kms:Decrypt
              - kms:DescribeKey
            Resource: '*'
          -
            Sid: PublisherAccess
            Effect: Allow
            Principal:
              AWS:
                - Fn::Join:
                  - ':'
                  - - 'arn:aws:iam:'
                    - Fn::ImportValue:
                        Fn::Sub: mxc-${AWS::Region}-${Environment}-publisher-${PublisherName}-accountid
                    - root
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
