AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Cloudformation template for media exchange subscriber setup.

Outputs:
  SubscriberAccountId:
    Description: Subscriber's AWS AccountId
    Value:
      Ref: SubscriberAccountId
    Export:
      Name:
        Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-accountid
  SubscriberCannonicalAccountID:
    Description: Subscriber's Cannonical AccountId
    Value:
      Ref: CannonicalAccountID
    Export:
      Name:
        Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-cannonicalaccountid
  SubscriberPrefix:
    Description: Subscriber's foldername for receiving content
    Value:
      Ref: Prefix
    Export:
      Name:
        Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-prefix
  SubscriberRole:
    Description: Subscriber Role to perform List* operations on the bucket
    Value:
      Fn::GetAtt: CrossAccountRole.Arn
    Export:
      Name:
        Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-role
  SubscriberRoleName:
    Description: Subscriber Role to perform List* operations on the bucket
    Value:
      Ref: CrossAccountRole
    Export:
      Name:
        Fn::Sub: mxc-${AWS::Region}-${Environment}-subscriber-${SubscriberName}-rolename

Metadata:

  License:
    Description: |
      Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.

      Permission is hereby granted, free of charge, to any person obtaining a copy of this
      software and associated documentation files (the "Software"), to deal in the Software
      without restriction, including without limitation the rights to use, copy, modify,
      merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
      permit persons to whom the Software is furnished to do so.

      THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
      INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
      PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
      HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
      OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
      SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Deployment Configuration"
        Parameters:
          - Environment
      -
        Label:
          default: "Subscriber Configuration"
        Parameters:
          - SubscriberName
          - SubscriberAccountId
          - CannonicalAccountID
          - Email
          - Prefix

Parameters:
  Environment:
    Type: String
    Description: Deployment Environment Name
    Default: dev

  SubscriberAccountId:
    Type: String
    Description: The accountId of the Subscriber.
    ConstraintDescription: AccountId is a 12 digit number
    AllowedPattern: '^\d{12}$'

  CannonicalAccountID:
    Type: String
    Description: The Cannonical Account ID of the subscriber.

  Email:
    Type: String
    Description: The email address for the transfer notifications.

  SubscriberName:
    Type: String
    Description: A name for subscriber account.

  Prefix:
    Type: String
    Description: A folder name for shared content.

Resources:

  AutoNotifySubscriberRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Notify Content Published"
      EventBusName:
        Fn::ImportValue:
          Fn::Sub: mxc-${AWS::Region}-${Environment}-events
      EventPattern:
        source:
          - publisher.mxc.amazonaws.com
        detail-type:
          - Fn::Sub: 'source=s3:ObjectCreated:*,notify=auto,prefix=${Prefix}'
      State: "ENABLED"
      Targets:
        -
          Id: "SNSEvent"
          InputPath: $.detail
          Arn:
            Ref: "NotificationTopic"

  CustomNotifySubscriberRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Notify Content Published"
      EventBusName:
        Fn::ImportValue:
          Fn::Sub: mxc-${AWS::Region}-${Environment}-events
      EventPattern:
        source:
          - publisher.mxc.amazonaws.com
        detail-type:
          - Fn::Sub: 'source=ApplicationEvent,prefix=${Prefix}'

      State: "ENABLED"
      Targets:
        -
          Id: "SNSEvent"
          InputPath: $.detail
          Arn:
            Ref: "NotificationTopic"

  NotificationTopic:
    Type: AWS::SNS::Topic

  EventTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            Resource: '*'
      Topics:
        -
          Ref: NotificationTopic

  NotificationsSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint:
        Ref: Email
      Protocol: email
      TopicArn:
        Ref: NotificationTopic

  CrossAccountRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: Cross accont role for subscriber to list contents of the bucket.
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              AWS:
                Ref: SubscriberAccountId
            Action: 'sts:AssumeRole'

      Path: /
      Policies:
        -
          PolicyName: mxc-subscriber-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              # enable for root level access
              # -
              #   Effect: Allow
              #   Action:
              #     - s3:ListBucket
              #   Resource:
              #     Fn::Sub: arn:aws:s3:::mxc-${AWS::AccountId}-${AWS::Region}-${Environment}-publisherbucket-*
              #   Condition:
              #     StringEquals:
              #       s3:prefix: ''
              #       s3:delimiter: '/'
              -
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  Fn::Sub: arn:aws:s3:::mxc-${AWS::AccountId}-${AWS::Region}-${Environment}-publisherbucket-*
                Condition:
                  StringLike:
                    s3:prefix:
                      Fn::Sub: ${Prefix}*
              -
                  Effect: Allow
                  Action:
                    - s3:GetBucketLocation
                    - s3:GetBucketPolicyStatus
                    - s3:GetBucketVersioning
                    - s3:GetBucketPublicAccessBlock
                    - s3:GetBucketObjectLockConfiguration
                    - s3:GetBucketAcl
                    - s3:GetEncryptionConfiguration
                  Resource:
                    Fn::Sub: arn:aws:s3:::mxc-${AWS::AccountId}-${AWS::Region}-${Environment}-publisherbucket-*
              -
                Effect: Allow
                Action:
                  - s3:GetAccountPublicAccessBlock
                Resource: '*'
